name: Main branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compilation:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "~/build"
          key: cache-build
      - name: Compilation
        run: |
          mkdir -p ~/build
          mkdir -p build
          cp ~/build/* ./build/
          make
          cp ./build/* ~/build/
          cp webserv ~/build/
  leaks:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "~/build"
          key: cache-build
      - name: install valgrind
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
      - name: run valgrind
        run: |
          mkdir -p build
          cp ~/build/* ./build/
          cp ~/build/webserv webserv
          make leaks
  tests:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "~/build"
          key: cache-build
      - name: install valgrind
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
      - name: run tests
        run: |
          mkdir -p build
          cp ~/build/* ./build/
          cp ~/build/webserv webserv
          cp ~/build/*.out .
          make tests
          cp ./build/* ~/build/
          cp webserv ~/build/
          cp *.out ~/build/
  tests-integration:
    needs: [compilation, leaks, tests]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "~/build"
          key: cache-build
      - uses: actions/setup-python@v4
      - name: update
        run: sudo apt-get update -qq -y
      - name: Tests
        run: |
          mkdir -p build
          cp ~/build/* ./build/
          cp ~/build/webserv webserv
          make tests-integration
