name: Main branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compilation:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: build
          key: cache-build
      - name: compilation
        run: |
          make re
          pwd
  leaks:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: build
          key: cache-build
      - name: install valgrind
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
      - name: run valgrind
        run: |
          pwd
          ls build/
          make leaks
  tests:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: build
          key: cache-build
      - name: install valgrind
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
      - name: run tests
        run: make tests
  tests-integration:
    needs: [compilation, leaks, tests]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: build
          key: cache-build
      - uses: actions/setup-python@v4
      - name: tests integration
        run: make tests-integration
