name: Main branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilation:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compilation
      run: make
  leaks:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Valgrind
      run: |
        sudo apt-get update -qq -y
        sudo apt-get install -qq valgrind
        make leaks
  tests:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Tests
      run: |
        sudo apt-get update -qq -y
        sudo apt-get install -qq valgrind
        make tests
  tests-integration:
    needs: [compilation, leaks, tests]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Tests
      run: |
        sudo apt-get update -qq -y
        make tests-integration