name: Main branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compilation:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make
  leaks:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install valgrind
        run: sudo apt-get install valgrind
      - name: run valgrind
        run: make leaks
  tests:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install valgrind
        run: sudo apt-get install valgrind
      - name: run tests
        run: make tests
  tests-integration:
    needs: [compilation, leaks, tests]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: tests integration
        run: make tests-integration
