name: Main branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compilation:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "build"
          key: cache-build

      - name: Compilation
        run: make
  leaks:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "build"
          key: cache-build
      - name: Valgrind
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
          make leaks
  tests:
    needs: compilation
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "build"
          key: cache-build
      - name: Tests
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq valgrind
          make tests
  tests-integration:
    needs: [compilation, leaks, tests]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: "build"
          key: cache-build
      - uses: actions/setup-python@v4
      - name: Tests
        run: |
          sudo apt-get update -qq -y
          make tests-integration
